name: gaussdiff
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - arrow-cpp=21.0.0=hac1acdb_1
  - asttokens=2.4.1=pyhd8ed1ab_0
  - autograd-gamma=0.5.0=pyhd8ed1ab_1
  - aws-c-auth=0.9.0=hb25bd0a_2
  - aws-c-cal=0.9.2=h3ff94e8_1
  - aws-c-common=0.12.4=hb25bd0a_0
  - aws-c-compression=0.3.1=hb25bd0a_2
  - aws-c-event-stream=0.5.6=hb25bd0a_0
  - aws-c-http=0.10.4=hb25bd0a_0
  - aws-c-io=0.21.4=h3eb0749_0
  - aws-c-mqtt=0.13.3=hb25bd0a_0
  - aws-c-s3=0.8.7=h3ff94e8_0
  - aws-c-sdkutils=0.2.4=hb25bd0a_1
  - aws-checksums=0.2.7=hb25bd0a_1
  - aws-crt-cpp=0.34.0=h7934f7d_0
  - aws-sdk-cpp=1.11.638=hac3f51a_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - blas=2.305=openblas
  - blas-devel=3.11.0=5_h1ea3ea9_openblas
  - bottleneck=1.5.0=py39hf3d9206_0
  - brotli=1.0.9=h5eee18b_9
  - brotli-bin=1.0.9=h5eee18b_9
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.12.2=h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_0
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-version=12.9=h4f385c5_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - formulaic=1.2.0=py39hf3d152e_2
  - freetype=2.12.1=h267a509_2
  - future=1.0.0=pyhd8ed1ab_2
  - gettext=0.21.0=hedfda30_2
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - icu=73.1=h6a678d5_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - interface_meta=1.3.0=pyhd8ed1ab_1
  - ipykernel=6.29.3=pyhd33586a_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - jupyter_core=5.7.2=py39hf3d152e_0
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcblas=3.11.0=5_h0358290_openblas
  - libcurl=8.16.0=heebcbe5_0
  - libdeflate=1.22=hb9d3cd8_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_15
  - libgcc-ng=15.2.0=h69a702a_15
  - libgfortran=15.2.0=h69a702a_15
  - libgfortran-ng=15.2.0=h69a702a_15
  - libgfortran5=15.2.0=h68bc16d_15
  - libgomp=15.2.0=he0feb66_15
  - libgrpc=1.71.0=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblapacke=3.11.0=5_h6ae95b6_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=h46f56fc_2
  - libpng=1.6.43=h2797004_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=h6a678d5_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h934c35e_15
  - libstdcxx-ng=15.2.0=hdf11a46_15
  - libthrift=0.22.0=hd8eb582_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=1.3=hb25bd0a_0
  - libuuid=2.41.2=h5347b49_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=hfdd30dd_0
  - libzlib=1.2.13=h4ab18f5_6
  - lifelines=0.30.0=pyhd8ed1ab_1
  - llvmlite=0.43.0=py39h6a678d5_1
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-base=3.9.2=py39hbfdbfaf_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.1.2=pyhe01879c_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nomkl=3.0=0
  - numba=0.60.0=py39h0320e7d_0
  - numexpr=2.10.1=py39hd28fd6d_0
  - numpy=1.26.4=py39hc213724_1
  - numpy-base=1.26.4=py39hf387b04_1
  - openblas=0.3.30=h5426c36_2
  - openblas-devel=0.3.30=h557178c_2
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.6.0=h26f9b46_0
  - orc=2.2.0=h372e9aa_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.3.3=py39h505adc9_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.3.1=py39h06a4308_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - pot=0.9.5=py39h3b40f6f_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - prompt_toolkit=3.0.42=hd8ed1ab_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pybind11-abi=4=hd3eb1b0_1
  - pygments=2.17.2=pyhd8ed1ab_0
  - pynndescent=0.5.13=py39h06a4308_0
  - python=3.9.18=h0755675_1_cpython
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pyzmq=25.1.2=py39h6a678d5_0
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.2=h5eee18b_0
  - s2n=1.5.14=hdbd6064_0
  - scipy=1.13.1=py39heeff2f4_1
  - setuptools=68.2.2=py39h06a4308_0
  - shap=0.48.0=cuda126py39h0cbd2f0_1
  - six=1.16.0=pyh6c4a22f_0
  - slicer=0.0.8=pyhd8ed1ab_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - traitlets=5.14.2=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - tzdata=2024a=h04d1e81_0
  - umap-learn=0.5.3=py39h06a4308_0
  - unicodedata2=16.0.0=py39h8cd3c5a_0
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py39h06a4308_0
  - wrapt=1.17.3=py39hd399759_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xz=5.4.6=h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - alabaster==0.7.16
      - alembic==1.13.1
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astroid==3.1.0
      - async-lru==2.0.4
      - atomicwrites==1.4.1
      - attrs==23.2.0
      - autograd==1.8.0
      - autopage==0.5.2
      - autopep8==2.0.4
      - babel==2.14.0
      - backports-tarfile==1.1.1
      - beautifulsoup4==4.12.3
      - binaryornot==0.4.4
      - black==24.4.0
      - bleach==6.1.0
      - boto3==1.42.10
      - botocore==1.42.10
      - catboost==1.0.3
      - category-encoders==2.3.0
      - certifi==2024.2.2
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cliff==4.6.0
      - cloudpickle==3.0.0
      - cmaes==0.10.0
      - cmd2==2.4.3
      - colorlog==6.8.2
      - contourpy==1.2.1
      - cookiecutter==2.6.0
      - copulas==0.12.3
      - cryptography==42.0.5
      - ctgan==0.11.1
      - deepecho==0.7.0
      - defusedxml==0.7.1
      - diff-match-patch==20230430
      - dill==0.3.8
      - docstring-to-markdown==0.15
      - docutils==0.21.2
      - dython==0.5.1
      - exceptiongroup==1.2.1
      - faker==37.12.0
      - fastjsonschema==2.19.1
      - filelock==3.19.1
      - flake8==7.0.0
      - fonttools==4.51.0
      - fqdn==1.5.1
      - fsspec==2025.10.0
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - icecream==2.1.2
      - idna==3.7
      - imagesize==1.4.1
      - imbalanced-learn==0.7.0
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - inflection==0.5.1
      - intervaltree==3.1.0
      - ipython==8.18.1
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - isort==5.13.2
      - jaraco-classes==3.4.0
      - jaraco-context==5.3.0
      - jaraco-functools==4.0.1
      - jeepney==0.8.0
      - jellyfish==1.0.3
      - jinja2==3.1.3
      - jmespath==1.0.1
      - joblib==1.4.0
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.1
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.1
      - jupyterlab-widgets==3.0.10
      - keyring==25.1.0
      - kiwisolver==1.4.5
      - libzero==0.0.8
      - mako==1.3.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==3.0.2
      - more-itertools==10.2.0
      - mpmath==1.3.0
      - mypy-extensions==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.3
      - nbformat==5.10.4
      - networkx==3.2.1
      - notebook==7.1.3
      - notebook-shim==0.2.4
      - numpydoc==1.7.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - optuna==2.10.1
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - pathspec==0.12.1
      - patsy==0.5.6
      - pbr==6.0.0
      - pillow==10.3.0
      - plotly==5.21.0
      - pluggy==1.5.0
      - prettytable==3.10.0
      - prometheus-client==0.20.0
      - psutil==5.9.8
      - pyarrow==6.0.0
      - pycodestyle==2.11.1
      - pycparser==2.22
      - pydocstyle==6.3.0
      - pyflakes==3.2.0
      - pylint==3.1.0
      - pylint-venv==3.0.3
      - pyls-spyder==0.4.0
      - pynvml==11.5.0
      - pyparsing==3.1.2
      - pyperclip==1.8.2
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pyqtwebengine==5.15.6
      - pyqtwebengine-qt5==5.15.2
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.20.3
      - python-json-logger==2.0.7
      - python-lsp-black==2.0.0
      - python-lsp-jsonrpc==1.1.2
      - python-lsp-server==1.11.0
      - python-slugify==8.0.4
      - pytoolconfig==1.3.1
      - pytorch-tabnet==4.1.0
      - pytz==2024.1
      - pyxdg==0.28
      - pyyaml==6.0.3
      - qdarkstyle==3.2.3
      - qstylizer==0.2.3
      - qtawesome==1.3.1
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - rdt==1.18.2
      - referencing==0.35.0
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rope==1.13.0
      - rpds-py==0.18.0
      - rtdl==0.0.9
      - rtree==1.2.0
      - s3transfer==0.16.0
      - scikit-learn==1.0.2
      - sdmetrics==0.24.0
      - sdv==1.31.0
      - seaborn==0.13.2
      - secretstorage==3.3.3
      - send2trash==1.8.3
      - skorch==0.11.0
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - sphinx==7.3.7
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - spyder==5.5.4
      - spyder-kernels==2.5.1
      - sqlalchemy==2.0.29
      - statsmodels==0.14.1
      - stevedore==5.2.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==8.2.3
      - terminado==0.18.1
      - text-unidecode==1.3
      - textdistance==4.6.1
      - threadpoolctl==3.4.0
      - three-merge==0.1.1
      - tinycss2==1.3.0
      - tomli==2.0.1
      - tomli-w==0.4.0
      - tomlkit==0.12.4
      - torch==2.8.0
      - tornado==6.4
      - tqdm==4.62.3
      - triton==3.4.0
      - types-python-dateutil==2.9.0.20240316
      - ujson==5.9.0
      - uri-template==1.3.0
      - urllib3==1.26.20
      - watchdog==4.0.0
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - whatthepatch==1.0.5
      - widgetsnbextension==4.0.10
      - wurlitzer==3.0.3
      - yapf==0.40.2
      - zipp==3.18.1
prefix: /home/jie/anaconda3/envs/gaussdiff
